### ISSUE TITLE
Digital object file size appears as "NaN undefined" in Firefox

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#353]
## Describe the bug
In Firefox, the file size for a digital object does not display. Instead of the size, it is displaying it is a not-a-number undefined.

## To reproduce
1. Navigate to an object with a digital object available to view using the Firefox browser:  [https://dimes.rockarch.org/objects/SyeUfA7RSXAfpd6uCsCdnM](https://dimes.rockarch.org/objects/SyeUfA7RSXAfpd6uCsCdnM)
2. See the details about the object
3. Notice that instead of digital object file size, "NaN undefined" is displayed
4. Compare to Chrome and Safari, which have the file size info available.

## Error message or screenshots
![image](https://user-images.githubusercontent.com/15254041/107561544-a8794980-6bac-11eb-92ac-45f9a1aa86c8.png)

**Comment by helrond** [comment]
This was happening because the `content-length` header was not part of the response for a `HEAD` request made in Firefox (but that header was returned in Chrome and Safari). It seems like browsers may implement CORS headers differently. `Content-length` is *supposed* to be one of the [CORS safelisted response headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header) but apparently it wasn't part of that list originally, so 🤷 

After explicitly setting `content-length` to be exposed on the resources being requested (PDFs) in AWS S3 this problem was resolved.
