### ISSUE TITLE
Improve UX for application of filters

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#361]
## Is your feature request related to a problem? Please describe.
User testing showed that users pressed the dates "Apply" button as a way to apply all filters because they were not aware that the results were dynamically updating based on their selections.

## Describe the solution you'd like
1. Change the button text to "Apply Dates"
3. Update the styles of the date filter button to be less prominent. Consider a smaller version of the "Filters" button styles on the search results page.
2. Apply some indication that the filters/facets have been applied. Consider a11y in this solution.

## Describe alternatives you've considered
Moving Apply button to top of modal and have it apply to all filters. However, this would introduce other issues because available facets would not update when others were selected.

**Comment by helrond** [comment]
I'm thinking it may make sense to take a bit of an incremental approach to this one, and address the button first, then test again and see if the problem persists. Because this is an issue that doesn't block users, I'm pretty cognizant that we don't want to do something that will make things worse, and every solution that I can think of to add an indication that filters or facets have been applied has pretty major drawbacks:
- adding an additional loading indicator makes the UI busier, and will likely end up being more confusing for users
- displaying the number of results seems at first like a good option, but the numbers in facet counts refer to individual match counts, rather than collection results. Displaying the count of collection results would be confusing because it wouldn't reconcile with the facet counts, and displaying the individual match count would provide dissonance between the filter modal and the main search results page.

**Comment by HaSistrunk** [comment]
Agreed. And agreed that the key point here is that currently we are not blocking/slowing users, so it's important to weigh the drawbacks from any changes against what we know to be a minor current issue.
