### ISSUE TITLE
Make use of headings in agent description

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#508]
## Is your feature request related to a problem? Please describe.
For some agents, the descriptions/bios are very long. For an already text-heavy site, this can make it difficult to parse the text and find relevant information. In usability testing we observed multiple users using Ctrl-F to find specific information because the text was difficult to scan.

There are currently headings included in some bios like [JDR Jr's](https://dimes.rockarch.org/agents/StJ2oY6P3jzUEnLxquKVLT), but the headings have not been preserved in import and appear simply as paragraph text.

## Describe the solution you'd like
If possible, preserve existing headings when importing agent description. Heading in the text should start at `h4` if we make "Description an `h3` as suggested in issue #507 ).

cc @rpappous

**Comment by helrond** [comment]
This one is going to be tricky for a couple of reasons:
- Headings in agent notes are currently not distinguished from surrounding text in any way in ArchivesSpace, so there is nothing in the source data to tell us that the headings are headings. 
- While it is possible to wrap notes in HTML, that is a practice we have moved away from because it introduces challenges both in producing consistent display as well as machine parsing of notes. 
- Even if we did want to wrap headings in some sort of tag to indicate that they are headings, we'd want it to be a more generic indication of a heading, rather than specific h-level, since we may change the HTML structure of pages in the future.
- One possible solution is to wrap headers in an `emph` tag, which is designed to be used for [formatting purposes](https://eadiva.com/2/emph/). We'd have to check if/how this tag comes through in JSON, and this also feels a bit like tag abuse.
- Another possibility may be to add multiple bioghist notes for each section, which would allow us to add titles for each section. We'd have to make additional changes to DIMES for these scenarios.
- Finally, the solution here may just simply be to write more concise bioghist notes. Politically, that may be a tall ask, though.

**Comment by HaSistrunk** [comment]
Ok yes. This does not feel like something we should solve in the code at this point, because the `emph` tag solution feels like an imperfect work-around, does nothing for accessibility for folks who might try to use headings to navigate quickly between sections with a screen reader, and I'm not sure it would add very much visually to what we already have, which at least does offset the "headings" as their own paragraphs.

I'd vote to do nothing to DIMES, but communicate our observation that really long biohist text is not easy to scan and users were trying things like CTRL-F to find the information they needed quickly.
