### ISSUE TITLE
Adding timestamp to DatePicker 

### ISSUE THREAD

**Issue by kcloud** [RockefellerArchiveCenter/dimes#528]
We're wanting to add a timestamp to our DateTimePicker calendar, so archivists may schedule appointments. However, the current component (https://github.com/reecelucas/react-datepicker) does not include a timestamp. There seem to be many options. For a pull request and future enhancements, do you have a recommended integration?

**Comment by helrond** [comment]
I don't have a recommended library, but something that is important to us is ensuring we don't take a step backwards in terms of accessibility. With these kinds of elements keyboard navigation is important (and can be tricky!) so that would be my primary concern.

A couple of other questions:
- Are we also going to need to look at what data is sent to Aeon? Do we need to add an additional field?
- Is this intended to integrate/interact in some way with the appointment scheduling feature in Aeon? I don't know a lot about that, but had some conversations with Atlas that indicated that it might be hard to do that given the current Aeon integration pattern (POST requests with data).

**Comment by kcloud** [comment]
I concur with concerns for accessibility as well as future maintenance/dependency management.

- I don't believe that Aeon supports time data within its date field. I think we'll need an additional field. 
- I do **not** expect to integrate with appointment scheduling in Aeon at this time. Our conversations with Atlas on the subject have been similar, and we have internal workarounds rather than using the API.

**Comment by helrond** [comment]
Thanks @kcloud - so we're going to need to make changes to Request Broker as well to support sending an additional field to Aeon. Off the top of my head I think that will likely need to happen [here](https://github.com/RockefellerArchiveCenter/request_broker/blob/base/process_request/routines.py#L220)

**Comment by ctgraham** [comment]
@chryslovelace, I think I need you to participate in this repo before I can assign the issue to you.

We've used [React Date Picker](https://github.com/Hacker0x01/react-datepicker/) for our proposed implementation.

Some challenges we discussed:
- The [add-datetime-picker](https://github.com/ulsdevteam/dimes/tree/add-datetime-picker) branch has numerous unrelated commits currently in ulsdevteam.
- We'll want many configuration possibilities, hopefully without the need to customize code for each, e.g.:
  - implementors may wish to only request dates, rather than datetimes ([current Rockefeller implementation](https://github.com/RockefellerArchiveCenter/dimes/blob/28ab5a573577a783a470518752f810cd789400f4/src/components/ModalMyList/index.js#L296-L309))
  - implementors may wish to [block weekends](https://github.com/ulsdevteam/dimes/blob/ae5a3b0827ae20ed29f071c0e69e865cd05d8aca/src/components/Inputs/index.js#L64-L67)
  - implementors of the time widget may wish to [limit hours](https://github.com/ulsdevteam/dimes/blob/ae5a3b0827ae20ed29f071c0e69e865cd05d8aca/src/components/Inputs/index.js#L68-L71)
  - implementors may wish to query an Aeon API (when available), as [Aeon exposes `openHours` for a `ReadingRoom`](https://support.atlas-sys.com/hc/en-us/articles/360011918933-Aeon-API#h_01G65S278QM44X1E0N0PNHF95R).
  - implementors may wish to set a [lead time](https://github.com/ulsdevteam/dimes/blob/ae5a3b0827ae20ed29f071c0e69e865cd05d8aca/src/components/Inputs/index.js#L83-L84) for requests.
