### ISSUE TITLE
Add component for loading indication

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/dimes#67]
## Is your feature request related to a problem? Please describe.
There are a number of places where data is loaded into the interface in an asynchronous way, and we need to indicate to users that this is happening.

## Describe the solution you'd like
A reusable component which indicates some action is taking place. Some options:
- https://www.npmjs.com/package/react-loading-skeleton
- https://www.npmjs.com/package/react-loading-overlay
- https://www.npmjs.com/package/react-spinners

## Additional context
@HaSistrunk are there accessibility issues we should be aware of?

**Comment by HaSistrunk** [comment]
There's a WCAG success criteria related to this: [https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html). A few things:

- If something is loading for awhile, there should be some kind of loading message that is announced by the screenreader, probably by moving focus to a 'loading' message
- We should be clear with controls like buttons that change the page content so that it is clear what they will do
- We can use [ARIA live regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) to announce a change to screenreaders. See [aria live regions in react](https://almerosteyn.com/2017/09/aria-live-regions-in-react) and the [aria-react-live package](https://www.npmjs.com/package/react-aria-live)
- We can use focus management to shift focus somewhere when something changes on the page. Like shifting focus to a new heading when new content is loaded, which will indicate to screenreaders that there is a change. In that way we wouldn't always need aria-live. 

There is a usability balance between screenreader chattiness and interruption, and letting the user know key things that they need to know.
