### ISSUE TITLE
Agent page "source" note does not display if the source is RAC

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#686]
## Describe the bug
The narrativeDescriptionSource in AgentNote is not displaying if it is "Rockefeller Archive Center". The UI just displayed "Source:" with no value. It works fine if the source is Wikidata/Wikipedia.

## To reproduce
1. Go to Nelson's agent page, which has a description note that is pulled from RAC description [https://dimes.rockarch.org/agents/nQV9zedPVBqFgyGrXPQvBw](https://dimes.rockarch.org/agents/nQV9zedPVBqFgyGrXPQvBw)
3. Scroll down to the bottom of the Agent description note
4. See that there is no source noted.

## Expected behavior
The source for an ArchivesSpace description note should be "Rockefeller Archives Center"

## Error message or screenshots
<img width="907" alt="image" src="https://github.com/RockefellerArchiveCenter/dimes/assets/15254041/e6cb9434-ce3a-4e8e-8463-3ebb03370cc0">

## Impact on your work
Researchers need this data to understand where this info is coming from.

**Comment by helrond** [comment]
The reason this empty "Source" is showing up is because of how the translation was implemented. There is lingui Select component there, but it's looking for a null value that will never exist because we set the variable it's looking at to an empty string.

However, based on my recollections and what I'm seeing in the code, I'm thinking the source was only designed to show up when it's something _other_ than "Rockefeller Archive Center" because the presumption is that otherwise everything on the site is coming from us (based on how things are branded and presented). It seems kind of weird to have one piece of text be attributed to the RAC when everything else is not.

**Comment by HaSistrunk** [comment]
Ah, that makes sense re: translation implementation.

>However, based on my recollections and what I'm seeing in the code, I'm thinking the source was only designed to show up when it's something other than "Rockefeller Archive Center" because the presumption is that otherwise everything on the site is coming from us (based on how things are branded and presented).

That was initially true in the design, but testing showed us that [that approach wasn't actually clear to users](https://github.com/RockefellerArchiveCenter/dimes/issues/507), so we changed it to list the source either way. I think partially because once folks saw that sometimes that source was _not_ the RAC, they wanted confirmation for that particular description when it _was_ the RAC.
