### ISSUE TITLE
BackstopJS tests not loading object data from mock requests

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/dimes#738]
## Describe the bug
BacktopJS tests that include mock requests to Request Broker are not functioning correctly - object data is not displayed.

## To reproduce
1. Run DIMES locally
2. In another terminal, run the backstopJS tests usuing `yarn backstop-test`
3. See the resulting tests on the My List page and in the request modals that show collection info, but not the associated archival objects.

## Expected behavior
The test snapshots should match the DIMES UI and include the archival object data that has been added to the users list. That data is in the mock requests located in the `backstop_data/request_reference` directory.

## Error message or screenshots
Screenshot of My List test:
<img width="759" alt="image" src="https://github.com/user-attachments/assets/06567b67-ae27-44ae-9cd5-0834894bfa1f">

## Impact on your work
Impacts our ability to the UI for unintended changes.

**Comment by helrond** [comment]
OK I totally rubber ducked myself into figuring this out!

What's happening is that a request is being made behind the scenes to the browser's localStorage, and then that data is used to filter out any items that might have been removed from the list: https://github.com/RockefellerArchiveCenter/dimes/blob/base/src/components/PageMyList/index.js#L264-L266

Because the "browser" storage in this case is empty, the `fetchMyList` function returns an empty list, which then filters out all of the items. 

Solution-wise, I think we need to either find a way to mock that `fetchMyList` function or the browser localStorage state.
